; Synchro-Wordle installer data for install-xtrn.js

Name: Synchronet Wordle
Desc: A Wordle clone written to work on synchronet BBSes.
By:   Dylan Calvin
Cats: Games
Subs: Puzzle, Javascript
Inst: 2026/07/10

[prog:WORDLE]
cmd = ?wordle
settings = XTRN_MULTIUSER
required = true